//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NITechTimetableConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NITechTimetableConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ファイルが見つかりません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました
        ///------------------------
        ///{0}
        ///------------------------
        ///時間割が配布されているそのままの状態から編集されている可能性があります
        ///ダウンロードしてから一切変更を加えていない状態のXLSXファイルを指定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力が無効か、入力されたファイルがXLSXファイルへのパスではありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInputInvalidOrNonXLSX {
            get {
                return ResourceManager.GetString("ErrorInputInvalidOrNonXLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの読み書きに失敗しました。変換対象のファイルや変換後のファイルと同名のファイルを開いている場合は閉じてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorIOException {
            get {
                return ResourceManager.GetString("ErrorIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注意：1年生向けの時間割表の変換と一部の教科の変換には対応していません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageCaution {
            get {
                return ResourceManager.GetString("MessageCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換が完了しました！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageConvertComplete {
            get {
                return ResourceManager.GetString("MessageConvertComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NITechTimetableConverter by Punyo a.k.a こ゛玉き巻しだ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageCredit {
            get {
                return ResourceManager.GetString("MessageCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ------------------------ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageDivider {
            get {
                return ResourceManager.GetString("MessageDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換対象の時間割のXLSXファイルへのパスを入力してください： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageEnterPath {
            get {
                return ResourceManager.GetString("MessageEnterPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換対象のXLSXファイルから講義情報を抽出しています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageExtractingLectureInfo {
            get {
                return ResourceManager.GetString("MessageExtractingLectureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   講義情報抽出完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageExtractingLectureInfoComplete {
            get {
                return ResourceManager.GetString("MessageExtractingLectureInfoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GitHub：https://github.com/Punyo/NITechTimetableConverter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageGitHubURL {
            get {
                return ResourceManager.GetString("MessageGitHubURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換後のXLSXファイルを開いています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageOpeningConvertedXLSXFile {
            get {
                return ResourceManager.GetString("MessageOpeningConvertedXLSXFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再試行する場合は&lt;Enter&gt;を押してください...
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageRetry {
            get {
                return ResourceManager.GetString("MessageRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シートの変換を開始しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageStartConvert {
            get {
                return ResourceManager.GetString("MessageStartConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   警告：このツールは国立大学法人名古屋工業大学や同法人に属する組織からの公式な承認を受けたものではありません
        ///また、このツールを使用したことに起因する如何なる損害も制作者は責任を負いかねます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageWarning {
            get {
                return ResourceManager.GetString("MessageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テンプレートに講義情報を書き込んでいます... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageWritingLectureInfo {
            get {
                return ResourceManager.GetString("MessageWritingLectureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   講義情報書き込み完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageWritingLectureInfoComplete {
            get {
                return ResourceManager.GetString("MessageWritingLectureInfoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X：https://x.com/rolled_omelette に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageXURL {
            get {
                return ResourceManager.GetString("MessageXURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] XLSXTemplate {
            get {
                object obj = ResourceManager.GetObject("XLSXTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
