//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NITechTimetableConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NITechTimetableConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   注意：このツールは国立大学法人名古屋工業大学や同法人に属する組織からの公式な承認を受けたものではありません
        ///また、このツールを使用したことに起因する如何なる損害も制作者は責任を負いかねます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageCaution {
            get {
                return ResourceManager.GetString("MessageCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NITechTimetableConverter by Punyo a.k.a こ゛玉き巻しだ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageCredit {
            get {
                return ResourceManager.GetString("MessageCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ------------------------ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageDivider {
            get {
                return ResourceManager.GetString("MessageDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シート内の時間割が記述されている部分の範囲を指定してください（例：A3:AJ93）： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageEnterArea {
            get {
                return ResourceManager.GetString("MessageEnterArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換対象の時間割のXLSXファイルへのパスを入力してください： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageEnterPath {
            get {
                return ResourceManager.GetString("MessageEnterPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル内の変換対象の時間割のシート名を入力してください（例：3年前期）： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageEnterSheet {
            get {
                return ResourceManager.GetString("MessageEnterSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] XLSXTemplate {
            get {
                object obj = ResourceManager.GetObject("XLSXTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
